### ISSUE TITLE
Linux input issues / Dead keys not working

### ISSUE THREAD

**Issue by niiico69** [Miodec/monkeytype#531] opened 2020-11-04 10:04 UTC
Taking the test with french, words with ^ are not registered
Can't type êôî…
Using a custom keyboard with a bépo layout and Linux, but these points shouldn't be a problem

**Comment by Miodec** [comment] 2020-11-04 17:33
Disable layout override - it will cause issues - then try again.

**Comment by niiico69** [comment] 2020-11-05 09:54
This is not working, with or without layout override.

**Comment by Miodec** [comment] 2020-11-05 19:47
What operating system are you running

**Comment by raulsaavedr** [comment] 2020-11-15 21:46
Hello guys, currently I've the same problem, in this case with spanish and special character e.g **ñ** or words with (**´**) like acci**ó**n , significar**á**, etc

**Comment by denislee** [comment] 2020-12-04 01:22
I'm having this same issue. But this is occurring only on chrome based browsers (like the qutebrowser that I'm currently using), but I don't see any issues using Firefox. 

I encourage you guys to try it on Firefox. I know it's a hasse, but it seems to be working there.

**Comment by aaronrancsik** [comment] 2021-01-12 17:23
Helló,
Yup the same problem here on Linux with English international layout and Hungarian accents ő, ű registered without dead key, like o u.
And only with chromium based Brave but Firefox works fine.

**Comment by koldaman** [comment] 2021-02-01 12:54
Same here with czech characters like ď, ť and capital ones like ĚŠČŘŽÝÁÍÉ that needs to be typed with typing sequence of two keys. Firefox is ok with it, but Chrome (Brave, Vivaldi, ...) fails to detect them right. Fix would be much appreciated.

**Comment by SeerLite** [comment] 2021-02-01 20:21
Monkeytype uses `keydown` events for the typing, and Chromium currently has a bug where the entered key has no accents/dead key symbols: https://crbug.com/1135952. This affects all Chromium-based browsers on Linux.
Technically this is also a bug in Firefox, but it can be worked around by using an invisible, always focused `<input>` element behind the test. This workaround doesn't work on Chromium.

For now all we can do is either wait for the Chromium bug to be fixed or rewrite Monkeytype completely to use the text from `<input>` instead of individual keypresses, but this would conflict with the current way anti-cheat works (AFAIK).

**Comment by aaronrancsik** [comment] 2021-03-02 02:39
No longer work with Firefox... not even from Firefox ESR. 
Maybe it's a client bug. Someone should confirm it.
I guess some change had been made on the site not in the browser.. could you please revert it? or at least support firefox's behavior as it was? Tanks!  
Cheers.

**Comment by Meknassih** [comment] 2021-03-19 22:48
Hello, I have been having this issue on Firefox, Windows 10 for a while. I’m using French BÉPO layout. I also noticed the **ç** character is always registered as wrong.

**Comment by mrBen** [comment] 2021-04-05 20:05
Hello all, I have the issue on Firefox, Fedora. The bug appear both with bépo and us-intl.

**Comment by gregseth** [comment] 2021-04-07 19:46
Same problem here with Safari & Firefox on macOS 11.2 using bépo layout. As mentioned in a previous comment not only dead keys (such as ^ or ¨) are not registered as such and the plain character is typed, but ç is wrongly typed as m and any character requiring a key combination (alt + key) are simply ignored.

**Comment by Meknassih** [comment] 2021-04-08 09:37
I can confirm having the same behaviour as gregseth describes it.

**Comment by Zuyoutoki** [comment] 2021-04-09 03:52
I can confirm having the issue with dead keys. Any ideas on how to fix?

Here's some info about what I have : 
```
> uname -srvmo
Linux 5.11.8-arch1-1 #1 SMP PREEMPT Sun, 21 Mar 2021 01:55:51 +0000 x86_64 GNU/Linux

> firefox --version
Mozilla Firefox 87.0

> localectl status
   System Locale: LANG=en_US.UTF-8
       VC Keymap: us
      X11 Layout: us
       X11 Model: pc104
     X11 Variant: intl
```

**Comment by edowado777** [comment] 2021-04-11 13:52
hello, I'm also using Firefox, and before Chrome, and the letter "ê" didn't work !

**Comment by Miodec** [comment] 2021-04-11 15:52
Sadly this needs an input system rewrite, not sure when it will be fixed as I'm focusing on multiplayer at the moment

**Comment by gregseth** [comment] 2021-04-11 16:00
Yeah but multiplayer is kind of secondary for people who can’t play…
May be have a look at http://dactylotest.free.fr/dactylotest/ which manages this correctly.

**Comment by Meknassih** [comment] 2021-04-12 11:20
@gregseth Dude we are like 10 people out of thousands of users that are having this problem so, if anything, _we_ are secondary here...

**Comment by Zuyoutoki** [comment] 2021-04-12 20:40
@Meknassih I disagree. I think being unable to properly type on a typing test website is _not_ secondary. This is free software, so I understand we can't expect the main dev to solve an issue not so many people have, but I still think this is an important issue considering it prevents people from typing during a typing test. Let's gather more data and try to figure out what exactly is causing the issue.

Some are saying that the issue was not there on some browsers at some point, so the next step should be to figure out which version of MonkeyType works with dead keys. Maybe the bug was caused with a browser update at some point and the fix should be done on their side. What's for sure is that we need more info about when dead keys are working, and when they aren't. I can try a bunch of version with Firefox 87.0 and report back with the results.

A volunteer to test different browsers versions for the latest MonkeyType release?

**Comment by aaronrancsik** [comment] 2021-04-12 20:49
@Zuyoutoki Some comments above @SeerLite made an explanation about the bug.

**Comment by Zuyoutoki** [comment] 2021-04-12 21:09
Oh, that's right, thanks. Since there are already issues opened with both chromium and firefox and the problem can't be fixed in monkeytype code without rewriting a good chunk of code, maybe waiting it out is the better course of action. Nevermind my last message then

**Comment by zeGolem** [comment] 2021-04-26 13:35
Doesn't work for me, my user agent:
`Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0`
I'm using the alternate AZERTY layout on Linux.

**Comment by Miodec** [comment] 2021-09-29 14:43
The inupt rewrite is live now on the main site. Give it a quick test and let me know.

**Closed** 2021-09-29 23:22 UTC
Labels: bug, waiting for update

**Comment by aaronrancsik** [comment] 2021-09-30 06:29
I've just tested every Hungarian accents lowercase and capital on `us+altgr-intl` layout and all works perfectly thank you for the fix!! <3

**Comment by mrBen** [comment] 2021-09-30 17:38
fedora firefox + bépo seems to work fine now, thanks for the fix

**Comment by Zuyoutoki** [comment] 2021-10-11 01:24
Fixed for me. Thanks!
