### ISSUE TITLE
Typing in Russian doesn’t work

### ISSUE THREAD

**Issue by vintagentleman** [Miodec/monkeytype#1677] opened 2021-07-25 09:16 UTC
**Describe the bug**

Trying to type in Russian inserts English characters instead.

**Did it happen in incognito mode?**

Both in incognito mode and when logged in.

**To Reproduce**

1. Go to _Settings_ → _Behavior_.
2. Select Russian as the language group.
3. Set up a typing test.
4. Switch the system layout to Russian and try to press any key.
5. The corresponding English key gets typed in instead.

**Expected behavior** The key gets typed in as usual.

**Screenshots**

![Peek 2021-07-25 11-52](https://user-images.githubusercontent.com/26284913/126894058-bdc427e8-7e5e-4718-93da-e4b0858114d1.gif)

**Desktop**

- OS: Ubuntu 20.04.2 LTS
- Browser: Google Chrome
- Browser Version: 92.0.4515.107

**Comment by Miodec** [comment] 2021-07-25 20:06
Is your layout override enabled in the settings? Make sure its set do default.

**Comment by vintagentleman** [comment] 2021-07-25 20:20
Yeah, it’s set to default, pretty sure I haven’t ever touched this setting.

**Comment by Miodec** [comment] 2021-07-25 20:48
Yeah, as in your other issue - should be fixed with the input rewrite.

Could you just verify that it works here: https://seerlite.github.io/monkeytype/issue/531-input-rewrite/

**Comment by vintagentleman** [comment] 2021-07-26 19:19
> Could you just verify that it works here: https://seerlite.github.io/monkeytype/issue/531-input-rewrite/

Thank you, I’ve checked it out. Typing in Russian seems to be working fine, either with opposite Shift mode enabled or not.

However, when typing in English, the issue with right-shift keys not working in opposite Shift mode does persist.

**Comment by Miodec** [comment] 2021-07-28 12:14
Duplicate of #531

**Closed by Miodec** 2021-07-28 12:14 UTC
Labels: bug, on hold
