### ISSUE TITLE
Theme got messed up when clicking on the theme button with custom theme

### ISSUE THREAD

**Issue by pingshunhuangalex** [Miodec/monkeytype#567] opened 2020-11-11 09:41 UTC
- Make sure you are using a custom theme
- Clicking on the theme button at the bottom of the screen
![image](https://user-images.githubusercontent.com/17170199/98794993-cf18ce80-245d-11eb-893d-0b15122e6752.png)
- Click away without switching to any other theme
- The theme gets reverted to the most recent preset theme but messed up as you can see some elements in the chart are still using the colours defined in the custom theme
![image](https://user-images.githubusercontent.com/17170199/98795408-4a7a8000-245e-11eb-8d1e-0ace13eb3e74.png)

**Comment by Miodec** [comment] 2020-11-11 13:25
Can't reproduce. I made a slight change to the custom themes recently so try to clear cache and try again.

**Comment by pingshunhuangalex** [comment] 2020-11-11 17:06
Now the custom theme can't be saved at all...

**Comment by pingshunhuangalex** [comment] 2020-11-22 01:51
The custom theme can be saved after hard-refresh the site this morning. But the above issue is still there and by clicking on the theme button (not changing any theme) will still revert to the most recent preset theme with a messed up chart...

**Comment by Miodec** [comment] 2020-12-07 18:28
Should be fixed now

**Closed by Miodec** 2020-12-07 18:28 UTC
Labels: bug, can't reproduce
