### ISSUE TITLE
Restarting creates blank word tests

### ISSUE THREAD

**Issue by Sushi6006** [Miodec/monkeytype#718] opened 2020-12-15 10:20 UTC
**Did you make sure to clear cache before opening an issue?** 
Yes

**Describe the bug**
Using `Tab`-`Enter` to restart the test at the very last second while doing a timed test would create a new test with no words.

**To Reproduce**
1. Start a new timed test with 15 seconds
2. At the very last second, press `Tab` then `Enter`
3. If restart at the right time, the test will restart but no words will be given.

**Expected behavior**
An empty word test

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Browser: Chrome Version 87.0.4280.88 (Official Build) (x86_64)
 - Version: v1.6.6

**Additional context**
Need to be very nicely-timed.

**Comment by TheeKevin** [comment] 2020-12-15 15:36
I believe this is a duplicate of #548

**Comment by Miodec** [comment] 2020-12-17 16:18
Yeap, @Sushi6006 could you try again after clearing cache and report back in #548? I am pretty sure this should be fixed because I cannot get this to happen.

**Closed by Miodec** 2020-12-17 16:18 UTC
Labels: bug
