### ISSUE TITLE
smooth line scroll causes input to be ignored after the first 2 lines

### ISSUE THREAD

**Issue by duckyb** [Miodec/monkeytype#644] opened 2020-11-28 18:02 UTC
## Test stuck example:
![monkey-stuck](https://user-images.githubusercontent.com/27895007/100522817-04d2ec80-31ac-11eb-999e-c6de9c8c1615.gif)

As you can see from the reactive keyboard, it often happens that the **input is not detected unless I press spacebar**.

Please let me know if you need more info, I remain available.

**Comment by duckyb** [comment] 2020-11-28 18:04
Narrowing down when this happens:
- The test must scroll at least once
- It is always after the first character of the first word in a new line

**Comment by syedecryptr** [comment] 2020-11-29 06:26
Same issue happening to me too.

**Comment by Miodec** [comment] 2020-11-29 21:12
Yeah i found that its the smooth line scroll causing this, but I cant reproduce this. I need someone else to find it for me because I simply don't know where to look as its not happening for me

**Comment by duckyb** [comment] 2020-11-30 08:49
I tried to reproduce the issue in an incognito window, imported my settings.json in the incognito tab and tried a test. Everything still worked even with smooth scrolling.

So I thought it might be my account. I logged in on the incognito tab. Still not getting stuck.
I tried to logout on the regular tab, not getting stuck. Logged in again on the regular tab and still not getting stuck.

**Looks like logging out and logging in again fixes this issue, at least temporarily**

@syedecryptr can you verify this?

**Comment by syedecryptr** [comment] 2020-12-03 07:27
@duckyb  yes like logging out and logging in again fixes this issue, at least temporarily.

issue not occurring after I logged in again.

**Comment by Miodec** [comment] 2020-12-05 16:05
Ill close this for now. Let me know if it happens again

**Closed by Miodec** 2020-12-05 16:05 UTC
Labels: bug, can't reproduce
