### ISSUE TITLE
Allow multiple custom themes with names

### ISSUE THREAD

**Issue by pingshunhuangalex** [Miodec/monkeytype#545] opened 2020-11-08 04:45 UTC
Just discover the custom theme setting and absolutely love it. It'll be nice if multiple custom themes are supported and allow me to manage them by giving them different names.
![image](https://user-images.githubusercontent.com/17170199/98457276-6de0c900-21d9-11eb-9886-e39107262546.png)

**Comment by Miodec** [comment] 2020-11-10 13:31
Duplicate of #322

**Closed by Miodec** 2020-11-10 13:31 UTC
