### ISSUE TITLE
Make statistics of most commonly misstyped characters, character cominations /words

### ISSUE THREAD

**Issue by mrkvicka22** [Miodec/monkeytype#448] opened 2020-10-21 15:10 UTC
Statistics for each character. 

- accuracy for each character individually

- confidence/consistency for each character

- what character do you most commonly type instead of this one

- I am sure there is plenty more like these.

**Comment by Miodec** [comment] 2020-10-21 16:13
Duplicate of #44

**Closed by Miodec** 2020-10-21 16:13 UTC

**Comment by mrkvicka22** [comment] 2020-10-21 16:30
> 
> 
> Duplicate of #44

I read that one and did not consider it to be a duplicate :D
