### ISSUE TITLE
Sign up/in not working on firefox

### ISSUE THREAD

**Issue by TwoDigitsOneNumber** [Miodec/monkeytype#1345] opened 2021-05-03 13:44 UTC
issue:
The buttons `Sign In`, `Sign Up` and `Google Sign In` don't work on firefox. After pressing them, a yellow circle appears but nothing else happens.

os: windows 10
browser: firefox 88.0

additional info:
- firefox runs in private mode (i.e. cache and history get deleted when firefox is closed)
- firefox is running a bunch of addons (but even after removing all of them and restarting firefox and windows, the same thing happens)
- firefox has enhanced tracking protection enabled (but even after disabling enhanced tracking protection and restarting firefox and windows, the same thing happens)

EDIT: the same occurs on my mac running MacOS 10.14.6 with the exact same firefox configuration.

**Comment by nagromc** [comment] 2021-05-03 14:16
Came to report the bug, but you already did 👍 

Confirmed as well in Firefox 89.0b7 (64 bits) on Windows 10.

**Comment by Saint-dev** [comment] 2021-05-03 17:07
Getting below error when loading up the site in firefox private mode

![image](https://user-images.githubusercontent.com/25359372/116907808-13687880-ac10-11eb-85e7-c99de14384b0.png)

Possibly related to https://bugzilla.mozilla.org/show_bug.cgi?id=781982

**Comment by DaneEvans** [comment] 2021-05-04 01:15
Also in Chrome Version 89.0.4389.128 (Official Build) (64-bit) on win 10, 

seems to work again once you update to Version 90.0.4430.93 (Official Build) (64-bit)

**Comment by TwoDigitsOneNumber** [comment] 2021-05-04 06:14
> 
> 
> Getting below error when loading up the site in firefox private mode
> 
> ![image](https://user-images.githubusercontent.com/25359372/116907808-13687880-ac10-11eb-85e7-c99de14384b0.png)
> 
> Possibly related to https://bugzilla.mozilla.org/show_bug.cgi?id=781982

Thanks for your response.
Exiting private browsing mode solved the issue for me. To me, it looks like it might be related to the link you attached (just skimmed it though, and I have no experience in web development).

**Comment by Miodec** [comment] 2021-05-09 13:30
Are you guys still running into this issue?

**Comment by nagromc** [comment] 2021-05-10 07:42
@Miodec Yes. The problem still occurs on Firefox 89.0b10 (64 bits) on Windows 10 and 88.0.1 (64 bits) on Windows 10.

The devtool console still shows `Uncaught Error: InvalidStateError: A mutation operation was attempted on a database that did not allow mutations`.

**Comment by Miodec** [comment] 2021-05-10 11:47
As @TwoDigitsOneNumber mentioned it could be related to a Bug in firefox with private mode (all though that bug is marked as resolved). Are you using private mode?

**Comment by Saint-dev** [comment] 2021-05-10 14:02
was able to prevent error by setting dom.indexedDB.privateBrowsing.enabled to true in about:config

looks like this is something currently being worked on at https://bugzilla.mozilla.org/show_bug.cgi?id=1639542

**Comment by JosephHerreraDev** [comment] 2021-05-28 20:15
I have the same problem, but don't use private browsing.

**Comment by Miodec** [comment] 2021-06-09 12:59
Closing due to being an external issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1639542

**Closed by Miodec** 2021-06-09 12:59 UTC
Labels: bug

**Comment by Miodec** [comment] 2021-06-11 13:15
Temporary fix that seems to be working:
```
There's an about:config workaround by setting

dom.indexedDB.privateBrowsing.enabled to true

Of course this will forego the privacy guarantees of private browsing, but it's a tradeoff you can make.
```
