### ISSUE TITLE
Typing field blank if test restarted on 0

### ISSUE THREAD

**Issue by Gabe-H** [Miodec/monkeytype#548] opened 2020-11-08 07:36 UTC
Pressing tab+enter to start the test over right as the timer hits 0 makes it refresh with a blank typing field.

![image](https://user-images.githubusercontent.com/50390056/98459626-6bd32780-2151-11eb-9039-b2f70dd9177a.png)

**Comment by TheeKevin** [comment] 2020-11-09 21:00
How did you even manage to restart at exactly 0 seconds? I've tried to reproduce this but I can only get to 1 second before the test finishes.

**Comment by Gabe-H** [comment] 2020-11-09 22:05
> How did you even manage to restart at exactly 0 seconds? I've tried to reproduce this but I can only get to 1 second before the test finishes.

The number 0 doesn't show up, but if you try to time is where it _would_ show up, you can sometimes get it to go. I'm guessing its a timing issue between the countdown and loading the results

**Comment by TheeKevin** [comment] 2020-11-09 22:25
> > How did you even manage to restart at exactly 0 seconds? I've tried to reproduce this but I can only get to 1 second before the test finishes.
> 
> The number 0 doesn't show up, but if you try to time is where it _would_ show up, you can sometimes get it to go. I'm guessing its a timing issue between the countdown and loading the results

I see. I'm guessing that since you restarted when 0 should popped off the results were supposed to show up since it hit 0 seconds but since you hit restart when the results popped up it showed the test screen. The problem is that the test screen doesn't show up since the results are supposed to show up but since results can't show up it's in this infinite cycle so it just goes blank. I don't even know if that's the problem but we'll see if Miodec or another contributor fixes this problem. 

Quick Question: Does the page fix itself once you reload it? If so then this would probably be a low priority bug for Miodec since it can be resolved easily.

**Comment by Miodec** [comment] 2020-11-10 13:30
Ive had this issue a while ago and it was fixed. Now I can't reproduce it so I don't know what to do about it.

**Comment by TheeKevin** [comment] 2020-11-10 15:47
@Miodec I think you should close this issue if you can't reproduce it or find a problem within the coding. Even if it is reproducible then it should be somewhat easily reproducible if it's a bug affecting a lot of people.

**Comment by Miodec** [comment] 2020-11-10 18:08
@Gabe-H how consistently can you get it? And what browser?

**Comment by Gabe-H** [comment] 2020-11-13 18:23
@Miodec Chrome 86.0.4240.198 (Official Build) (64-bit) (cohort: 86_Win_198) </br>
When I first found the bug I hit it 5 times in a row before writing the issue. When I went back a day or two later, I could only get it every 2 or 3 tries. I'll try again now

**Comment by Gabe-H** [comment] 2020-11-13 18:43
[video of 3/5 successful fails](https://drive.google.com/file/d/1W4pgUDtgREnDikne8y7rwA36UEoCEs3Q/view)

**Comment by Miodec** [comment] 2020-12-17 16:17
Could you try again after clearing cache? I believe this should be fixed

**Comment by Miodec** [comment] 2020-12-17 16:19
Nevermind, only an issue with tab + enter. I was trying just tab with quick tab enabled. Fixing.

**Closed** 2020-12-17 16:22 UTC
Labels: bug
