### ISSUE TITLE
can type é

### ISSUE THREAD

**Issue by HonkHonk0734** [Miodec/monkeytype#1906] opened 2021-09-26 09:14 UTC
**Describe the bug** I cant type accented letters like é, So i have dead keys on so to type and ' i need to do ' + space and for é '  + e but while i am type this here in github this works but in monkeytype when i type é it does ' so dead keys are not working

 **Did it happen in incognito mode?**
No, it did not and going in incognito mode does not help the problem

- OS: [] <Linux Mint 20.2 x86_64 (XFCE edition)>
- Browser [] <chromium>
- Browser Version [] <94.0.4606.61>

**Comment by Miodec** [comment] 2021-09-26 14:04
Duplicate of #531, will be fixed by #1325

**Closed by Miodec** 2021-09-26 14:04 UTC
Labels: bug
