### ISSUE TITLE
Progress & Poetry Funbox

### ISSUE THREAD

**Issue by TheeKevin** [Miodec/monkeytype#1721] opened 2021-08-13 22:47 UTC
Yes I did clear my cache before this 

**Describe the bug**  You should be able to find it in the "reproduce" and expected result

 I did not try it on incognito mode as the conditions I'm in don't really allow me to try that.

**To Reproduce** 

1. Set your timer/progress to "mini" or "text"
2. Set your funbox to "poetry"
3. Do a test on "words" and you can choose any amount

**Expected behavior**  The limit should be the amount of words that you set it as.

**Screenshots**  
![Screenshot 2021-08-13 at 4 41 32 PM](https://user-images.githubusercontent.com/58377021/129424691-01fd978f-fc6a-45f6-bfb1-32ad26970c7f.png)

- OS: []  Chrome OS
- Browser []  Chrome
- Browser Version []  Version 88.0.4324.208 (Official Build) (64-bit)

**Additional context**

**Comment by UnrealApex** [comment] 2021-08-15 21:54
I assume the bug this caused by this line of code:https://github.com/Miodec/monkeytype/blob/dba17c2e7b098b85bed3f61e4a2e1de7c4718040/src/js/test/poetry.js#L2

`maxWords` is of type const, therefore it is immutable.

**Comment by Miodec** [comment] 2021-11-20 20:04
Fixed in #2069

**Closed** 2021-11-20 20:40 UTC
Labels: bug
