### ISSUE TITLE
Store custom themes

### ISSUE THREAD

**Issue by Miodec** [Miodec/monkeytype#322] opened 2020-08-26 20:22 UTC

**Comment by TheeKevin** [comment] 2020-11-09 21:08
I think this is a near duplicate of #547 and #545 combined.

**Comment by rizwanmustafa** [comment] 2022-01-15 06:01
@Miodec  Please assign me to this issue as I have started working on it.

**Comment by rizwanmustafa** [comment] 2022-02-26 02:23
To be closed #2589

**Closed** 2022-03-09 18:50 UTC
Labels: new feature, backend, frontend
