### ISSUE TITLE
Half Black screen

### ISSUE THREAD

**Issue by MysteriousLog6** [Miodec/monkeytype#1129] opened 2021-03-21 17:28 UTC
**Describe the bug**
Half of the screen turn black as soon as I start typing 

**Did it happen in incognito mode?**
No it did not ( I was unable to reproduce it after a few minutes (I went to another room and when I came back it was fixed))
**Unable to reproduce now**

**Desktop:**
 - OS:Windows
 - Browser: Edge
 - Version: 89

**Comment by Miodec** [comment] 2021-03-21 22:43
Im gonna close it for now since you cant reproduce it for now and didn't get a screenshot of the bug, so I'm not really sure where to start looking for it. Open another issue if you encounter it again.

**Closed by Miodec** 2021-03-21 22:43 UTC
Labels: bug

**Comment by MysteriousLog6** [comment] 2021-03-22 03:08
Ok! Will see if it happens again and will check system logs for anything when it does happen.
