### ISSUE TITLE
Pace caret improvements [Feature Request]

### ISSUE THREAD

**Issue by duckyb** [Miodec/monkeytype#454] opened 2020-10-22 14:08 UTC
I have thought of two improvements for the pace caret, I could even try to implement this myself if you agree that they would be good additions to have.

### 1. Add _personal average_ as a pace caret mode

Yes, I know I can set my personal average as a custom speed, but it would be nice to set it to personal average and make it raise by itself over time. (Completing tests consistently above average would slowly raise the average dynamically)

### 2. Dynamically change the pace caret speed based on mistakes.

At the moment there is a design flaw with the pace caret, if I write **numbee** instead of **number** and press spacebar, the pace caret skips ahead because the wrong word is not counted, but if I immedeately delete the wrong character and correct the word, the caret skips back because the word is now correct.
This visually causes the pace caret to keep skipping everywhere if mistakes are made and corrected often. Sometimes even going back and forth between lines.  
It would be much cleaner if the caret adjusted it's speed based on the mistakes made, so if a mistake was made it goes ever so slightly faster, and if it is corrected it slows down. This way if a mistake is made and corrected right away the pace caret will not jump around.

**Comment by duckyb** [comment] 2020-10-22 14:20
Just found #370 and #453 you can close this issue in favor of those if you prefer.

**Comment by Miodec** [comment] 2020-10-22 14:50
1. Yeap, duplicate of #370. Probably will work based on the average of your last 10 tests.

2. This would involve some weird maths that I really don't want to attempt at this moment - nor do I even have an idea on how to approach it. Plus - it already works.

**Closed by Miodec** 2020-10-22 14:50 UTC
