### ISSUE TITLE
Opposite shift mode, app hangs and I inevitably enter an incorrect letter

### ISSUE THREAD

**Issue by zenVentzi** [Miodec/monkeytype#1514] opened 2021-06-04 21:50 UTC
Cache cleared. Happens also in incognito mode. Chrome, latest, Windows 10.

When master mode enabled, oftentimes it hangs on some letter. Sometimes for a few seconds, other times just quick enough for me to have entered the next letter and to "die". When the hanging is the longer one, I can sometimes press any letter(wrong ones included) and nothing happens. Neither I "die" nor it moves on the next letter. Also, the default cursor isn't blinking.

**Describe the bug** 

All my settings exported below:

`{"theme":"serika_dark","customTheme":false,"customThemeColors":["#323437","#e2b714","#e2b714","#646669","#d1d0c5","#ca4754","#7e2a33","#ca4754","#7e2a33"],"favThemes":[],"showKeyTips":false,"showLiveWpm":false,"showTimerProgress":true,"smoothCaret":true,"quickTab":true,"punctuation":true,"numbers":true,"words":100,"time":30,"mode":"words","quoteLength":[1],"language":"english_10k","fontSize":15,"freedomMode":true,"difficulty":"master","blindMode":false,"quickEnd":true,"caretStyle":"default","paceCaretStyle":"default","flipTestColors":false,"capsLockBackspace":false,"layout":"default","funbox":"none","confidenceMode":"off","indicateTypos":false,"timerStyle":"text","colorfulMode":false,"randomTheme":"off","timerColor":"black","timerOpacity":"0.25","stopOnError":"off","showAllLines":true,"keymapMode":"off","keymapStyle":"staggered","keymapLegendStyle":"lowercase","keymapLayout":"qwerty","fontFamily":"Roboto_Mono","smoothLineScroll":false,"alwaysShowDecimalPlaces":false,"alwaysShowWordsHistory":true,"singleListCommandLine":"manual","playSoundOnError":false,"playSoundOnClick":"off","startGraphsAtZero":true,"swapEscAndTab":false,"showOutOfFocusWarning":true,"paceCaret":"off","paceCaretCustomSpeed":100,"repeatedPace":true,"pageWidth":"100","chartAccuracy":true,"chartStyle":"line","minWpm":"off","minWpmCustomSpeed":70,"highlightMode":"letter","alwaysShowCPM":false,"enableAds":"off","hideExtraLetters":true,"strictSpace":false,"minAcc":"off","minAccCustom":98,"showLiveAcc":false,"monkey":false,"repeatQuotes":"off","oppositeShiftMode":"on","customBackground":"","customBackgroundSize":"cover","customBackgroundFilter":[0,1,1,1,1],"customLayoutfluid":"qwerty#dvorak#colemak","monkeyPowerLevel":"off"}`

EDIT: just switched to "expert" mode and happened again.

EDIT2: it started happening in all mods. No high cpu or anything. If that matters.

EDIT3: I think it has a lot more to do with the "opposite shift mode" than the master or export modes. I made that conclusion by changing back and forth the "opposite shift mode". Every time I turn it on, I get the hang within a minute or two of typing. And when it is turned off, I haven't got it yet(10+ minutes)

**Comment by Miodec** [comment] 2021-06-04 22:59
Can you just do a quick test by resetting your settings to default values and only enabling the opposite shift mode?

**Comment by zenVentzi** [comment] 2021-06-05 05:30
Happened again.

Actions I did:

- reset settings
- turn on opposite shift
- turn on 10k words english 

Details:

It took me slightly more time(about 3 minutes of typing) but it hung. I wasn't in expert or master mode, so I didn't "die" but that one letter was "dead". E.g. after it "un-hangs" I move on with red-colored letters. Then I backshift to the letter that I think it hung, and it hangs/blocks on that (small)letter once again.

Then I backspace even to the letter before it "u" (the whole word was "Due"), then try to enter the blocked letter "e" again and it blocked for some seconds again, then moved on with errors. 

Then I backspaced, deleting the whole word, "Due" and started typing it anew and it didn't hang.

**Comment by Miodec** [comment] 2021-06-05 12:41
What keyboard layout are you using?

**Comment by zenVentzi** [comment] 2021-06-05 13:37
Qwerty

**Comment by Miodec** [comment] 2021-06-05 14:16
Does it happen if you just set "Criteria" as the custom text?

**Comment by zenVentzi** [comment] 2021-06-05 14:52
![image](https://user-images.githubusercontent.com/11378653/120895653-aab55700-c626-11eb-8bcc-20a755ac3717.png)
Yes, if we're talking about the same criteria. Now it just blocked on the "o"

**Comment by Miodec** [comment] 2021-06-05 14:58
No i mean doing something like this: 
![image](https://user-images.githubusercontent.com/13181393/120895854-ca448380-c616-11eb-992f-fe2020f7ee7c.png)

Does it still break then? Do you use any external programs that edit the input/keyboard events in any way?

**Comment by zenVentzi** [comment] 2021-06-05 15:50
I'm not sure if I see how that is different from what I did? Mine just has more text because it doesn't hang on every single word, it needs at least a couple of paragraphs of text to test.

I don't use any external programs for modifying the input

**Comment by Miodec** [comment] 2021-06-05 16:02
> Mine just has more text because it doesn't hang on every single word, it needs at least a couple of paragraphs of text to test.

To try and isolate the issue because I can't reproduce it. If I can't reproduce it I don't know where to look for the issue.

**Comment by zenVentzi** [comment] 2021-06-05 16:16
The app is more than fine without that feature for me. I guess we should close the issue if I can't provide more details. 

IMHO I really did give enough detail and spent enough time testing different details. Given the above, I don't know how much more I can do to isolate it. I mean what's next? Can't afford to re-install my OS just for that. If I come up with anything I'll share.

**Comment by justklauz** [comment] 2021-06-10 03:34
a bug appeared when you change the theme the word keeps changing randomly by itself

**Comment by Miodec** [comment] 2021-06-10 15:15
> a bug appeared when you change the theme the word keeps changing randomly by itself

Is this related to this issue? Can you explain it further / record it?

**Comment by justklauz** [comment] 2021-06-13 02:44
> > a bug appeared when you change the theme the word keeps changing randomly by itself
> 
> Is this related to this issue? Can you explain it further / record it?

When I change a theme, I start to type but I cannot type it till the end in word mode so the whole words change when I type a word

**Comment by Miodec** [comment] 2021-06-23 17:30
Possibly fixed by f8b19cf76e82739a7fe7a88976070e8f9357bc13 - please check

**Closed** 2021-07-04 19:36 UTC
Labels: bug, can't reproduce, waiting for update
