### ISSUE TITLE
Swedish layout does not work correctly

### ISSUE THREAD

**Issue by Proximyst** [Miodec/monkeytype#1684] opened 2021-07-28 06:28 UTC
**Describe the bug** 

When using a Swedish keyboard layout (both with and without dead keys), it effectively uses US layout. When pressing the keys for äöå, it does not produce this, and the key for `'` produces a `/` (which is _very_ frustrating when trying to do quotes and the likes). This only happens when typing in the main view of the site.

This happens in incognito mode.

**To Reproduce** 

1. Go to monkeytype.com and use a Swedish layout.
2. Press the key right of P and L; it should create one of åöä.
3. Now press escape and type öäå in the options searcher; it will work as expected.

**Expected behavior**

I expect the buttons for öäå to produce öäå.

**Screenshots** 

What ö produces:
![image](https://user-images.githubusercontent.com/19861299/127274277-f28c51f1-2b21-4dcf-81e4-6272cf10b7c1.png)
But works fine in options search:
![image](https://user-images.githubusercontent.com/19861299/127274295-beb5991b-8e4a-4fb4-9f3d-bfa841408275.png)

Same with key for `'`:
![image](https://user-images.githubusercontent.com/19861299/127274337-39d1c588-863c-4e7b-9cb5-c179f31b4454.png)
while:
![image](https://user-images.githubusercontent.com/19861299/127274350-1a7bd820-3f6f-4d8d-b075-e719d1854d65.png)

**Desktop:** 

- OS: Ubuntu 20.04 LTS; `5.8.0-63-generic #71~20.04.1-Ubuntu`
- Browser: Google Chrome (snap)
- Browser Version: `Version 92.0.4515.107 (Official Build) (64-bit)`

**Comment by Miodec** [comment] 2021-07-28 11:59
Linux doesnt like dead keys at the moment. This will be fixed by #1325

**Comment by Miodec** [comment] 2021-07-28 12:14
Duplicate of #531

**Closed by Miodec** 2021-07-28 12:14 UTC
Labels: bug

**Comment by uqs** [comment] 2021-07-28 12:41
additionally, Chrome 92 suffers from mishandling events in certain circumstances: https://bugs.chromium.org/p/chromium/issues/detail?id=1232428

**Comment by Miodec** [comment] 2021-07-28 12:48
> additionally, Chrome 92 suffers from mishandling events in certain circumstances: https://bugs.chromium.org/p/chromium/issues/detail?id=1232428

Permission denied.
