### ISSUE TITLE
Quick tab mode in Firefox and Safari tabs to browser tools

### ISSUE THREAD

**Issue by DataDavD** [Miodec/monkeytype#1209] opened 2021-04-09 03:21 UTC
When using `quick tab mode` in Firefox, hitting tab restarts monkey type test but also moves the current selection over to back button which causes next typing movement to typically activate the back button or something else with Firefox browser.  With same `quick tab mode` in Safari it restarts the test but tabs the selection up to the URL bar. Does not happen in Chrome. This renders the `quick tab mode` useless for Firefox/Chrome users. 

**Did it happen in incognito mode?**
Sometimes things work in incognito mode, which allows me to further track down the issue.

**To Reproduce**
1. Go to monkey type settings
2. Turn on quick tab mode
3. Run one test then hit tab to restart test
4. In Firefox the current selection should now be on back button, while in Safari it should be on/open the URL bar.

**Expected behavior**
Should work like chrome, no issue and restart test while keeping current selection in test.

Safari and Firefox Screenshots
[
![Screen Shot 2021-04-08 at 8 18 19 PM](https://user-images.githubusercontent.com/39511285/114123676-a4fdf800-98a7-11eb-8a30-2a08d7b3f442.png)
![Screen Shot 2021-04-08 at 8 18 33 PM](https://user-images.githubusercontent.com/39511285/114123679-a5968e80-98a7-11eb-8136-9b73541dfbc3.png)
](url)

**Desktop (please complete the following information):**
 - OS: macOS Catalina (10.15.7)
 - Browsers: Safari 14.0.3 & Firefox 87.0 (both most recent versions)

Thanks in advance for looking into this and making a great product.

**Comment by CrumblyLiquid** [comment] 2021-04-09 07:14
I'm running Windows 10 (19042.906) with Firefox 87.0 and couldn't reproduce this issue. Seems like it applies only to macOS.

**Comment by SeerLite** [comment] 2021-04-09 16:54
@DataDavD Can you check if you get the issue [here](https://seerlite.github.io/monkeytype/tmp/1209-quicktab/)?

**Comment by Miodec** [comment] 2021-04-09 17:21
It was Mac exclusive. Should be fixed now.

**Closed by Miodec** 2021-04-09 17:21 UTC
Labels: bug

**Comment by DataDavD** [comment] 2021-04-12 20:16
hey @Miodec thanks for the quick fix. Sorry for the late reply as well.  I can confirm it is fixed now.  Thanks again!!!!
