### ISSUE TITLE
Cannot write AltGr+ characters.

### ISSUE THREAD

**Issue by matgaj** [Miodec/monkeytype#504] opened 2020-10-30 08:57 UTC
In Polish some characters are typed by pressing a combination of RightAlt + *latin letter*. Alt+z = ż; Alt+x = ź and so on. The issiue I have is that when typing ż,ź,ć,ń,ą,ś,ł,ó and ę the site registers only the latin letter and not the special character.

**Comment by Miodec** [comment] 2020-10-30 13:59
Duplicate of #36

**Closed** 2020-10-30 13:59 UTC
