### ISSUE TITLE
Quote rating UI allows multiple ratings which go away after a refresh

### ISSUE THREAD

**Issue by Dorifor** [Miodec/monkeytype#2128] opened 2021-11-27 17:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Current Behavior

When I review / note a quote, it seems I can do it indefinitely without the need to refresh the page or anything.

Gif :  
![gif spam review](https://cdn.discordapp.com/attachments/551206727106822173/914204130845790258/SpamReview.gif)

### Expected Behavior

While in this case it proved useful because this quote was impossible to write, I don't think it's expected behavior, but let me know if I'm wrong.

### Steps To Reproduce

1. Go into quote mode
2. Finish it
3. Click on the little star in the "source" of the quote
![image](https://user-images.githubusercontent.com/28139590/143690908-6de54fd1-bf3f-4840-b900-5ec4e77002d9.png)
4. Put any note
5. Submit
6. Repeat 3/4/5

### Environment

- OS: Windows 10
- Browser: Firefox
- Browser Version: 94.0.1

### Did you check incognito mode?

- [ ] I have checked incognito mode

**Comment by Miodec** [comment] 2021-11-27 18:36
This is probably a UI issue as in the backend i replace the ratings. Do these rating changes persist if you refresh? Or do they revert?

**Comment by Dorifor** [comment] 2021-11-27 23:27
After some time I decided to retry it and it seems to be resolved, I don't really know what caused it though.

**Comment by Miodec** [comment] 2021-11-27 23:56
It has to be something very specific because i have not started fixing this issue yet

**Comment by Miodec** [comment] 2021-11-29 18:28
I cant reproduce this. Since @Dorifor cant either ill just close this. If this happens again comment.

**Closed by Miodec** 2021-11-29 18:28 UTC
Labels: bug
