### ISSUE TITLE
Dev training mode / language 

### ISSUE THREAD

**Issue by jadkhoury** [Miodec/monkeytype#573] opened 2020-11-11 13:16 UTC
Could be implemented as an additional language / dictionary that mixes 
- usual English words
- common code words (main, struct, double, int, float4x4, switch ...)
- common code characters (& | ( ) {} [] ; '' "" _ - + = ` )

I know that there are some websites where you can train at typing actual code but it's not really as fun and engaging as MonkeyType.

**Comment by Miodec** [comment] 2020-11-11 13:19
Duplicate of #535

**Closed by Miodec** 2020-11-11 13:19 UTC
