### ISSUE TITLE
Accuracy and WPM Live Count overlap

### ISSUE THREAD

**Issue by drosophominin** [Miodec/monkeytype#1477] opened 2021-05-27 16:54 UTC
**Describe the bug** 

**To Reproduce** 

1. Go to Settings
2. Under the _Hide Elements_ tab, enable Live WPM and Live Accuracy
3. Run any test

**Expected behavior** 

- OS: MacOS 
- Browser: Safari
- Browser Version: 14.0.3 

**Smartphone:**  NA

- Device: [] 
- OS: [] 
- Browser [] 
- Browser Version [] 

**Additional context**

**Comment by Miodec** [comment] 2021-05-27 22:04
This is a graphical issue with Safari. I've got no clue why its happening and I cant seem to find a way to fix it. You might wanna switch the timer style to `mini` to avoid this issue. Also duplicate of #1350, so closing.

**Closed by Miodec** 2021-05-27 22:04 UTC
Labels: bug
