### ISSUE TITLE
Save Screenshot cropping bug

### ISSUE THREAD

**Issue by andrew50git** [Miodec/monkeytype#2205] opened 2021-12-24 20:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Did you clear cache before opening an issue?

- [X] I have cleared my cache

### Current Behavior

When I click the "Save Screenshot" button, some text on the right is cut off. This doesn't completely break the feature, but it is kind of annoying.

![image](https://user-images.githubusercontent.com/64051994/147371792-83870182-6e9d-4af8-9395-a93d26bf5afb.png)

### Expected Behavior

The save screenshot button should not cut off the text on the right.

### Steps To Reproduce

1. open monkeytype.com
2. choose no punctuation or numbers, words, 10 words
3. finish test
4. click "save screenshot" button
5. paste image into paste-able area (for example a file explorer app or Discord)
6. You will see that the image is incorrectly cropped.

### Environment

- OS: Ubuntu 20.04.3 LTS x86_64
- Browser: Vivaldi
- Browser Version: 5.0.2497.32 (Stable channel) stable (64-bit)

### Anything else?

my monitor is 2560x1440 pixels

this bug also occurs on google chrome 96.0.4664.110 (Official Build) (64-bit)

### Did you check incognito mode?

- [X] I have checked incognito mode

**Comment by Miodec** [comment] 2021-12-24 21:22
Duplicate of #2054

**Closed by Miodec** 2021-12-24 21:22 UTC
Labels: bug

**Comment by Miodec** [comment] 2021-12-24 21:45
Just to confirm did you change any scaling or font size settings in the browser?
