### ISSUE TITLE
Can't type accented characters

### ISSUE THREAD

**Issue by dcasado** [Miodec/monkeytype#36] opened 2020-05-18 10:23 UTC
I'm having trouble using accented characters like á, é, í, etc in spanish. Those characters need two keys to be pressed to be registered, first the accent and then the letter. If I try to do that nothing happens, it's like those keystrokes are not been registered.

**Comment by Miodec** [comment] 2020-05-18 12:30
Okay, i figured it out and know what the issue is. Im not sure how to fix it yet, but at least i understand it. This is the same problem as #35, so ill close this one.

**Comment by Miodec** [comment] 2020-05-19 11:10
Hey, @dcasado, im super close to pushing this to the live version, just need to do final testing. Would you mind visiting https://monkey-type-dev-67af4.web.app/ and checking if everything is alright?

**Comment by dcasado** [comment] 2020-05-19 12:02
I just did a quick test and seems like it's visually not synced. With the first keystroke the cursor does not move but behind the scenes it checks the letter correctly and if I hit backspace to delete one letter the cursor moves forward instead of deleting the character. This leads to the strange behavior you see in the screenshot. First and second words I did not press backspace but in the third word I pressed it.

![image](https://user-images.githubusercontent.com/10188511/82323896-02136580-99d9-11ea-8162-fbb570e93e7f.png)

**Comment by Miodec** [comment] 2020-05-19 12:08
Thanks for testing. I know where the issue is, and it seems like its Firefox only. Chrome should work. Looking for solutions

**Comment by dcasado** [comment] 2020-05-19 12:23
Sorry I forgot to mention that I tested it on Firefox. Just tried on Chrome it seems to work perfect

**Comment by Miodec** [comment] 2020-05-19 12:52
K, firefox is super weird and doesnt react properly to the chrome solution. I added a 10ms delay to absolutely make sure the letters are going through, but it feels like a bad idea - not sure if 10ms will make a difference.

Basically in chrome by using `setTimeout` with a delay of `0` the callback function will be executed on the next event loop, but firefox doesnt behave that way and i dont know why. Maybe because chrome be its design uses more resources to be faster?

Give it another try, should be all good. Make sure to hard refresh to get the latest script.

On another note, firefox is also weird when sending keycodes for accented characters. In chrome, `´` and `á` are both keycode 229, which makes sense. But in firefox, the first accent character has the keycode of the keyboard key `219`, which is `[`. Its pretty weird, and this makes it so I can't underline the characters that are accented (while they are being typed)

**Comment by dcasado** [comment] 2020-05-20 08:21
Now on Firefox seems to work but there is one thing that worries me a bit. Like you said Firefox sends the wrong keycode when pressing the accent and in the app is marked as an error until I press the letter. Are those errors reflected on the accuracy at the end of the test?

**Comment by Miodec** [comment] 2020-05-20 15:34
> Like you said Firefox sends the wrong keycode when pressing the accent and in the app is marked as an error until I press the letter. Are those errors reflected on the accuracy at the end of the test?

Yeah, from my testing to create an accented character i had to press [ and then a letter. Since firefox sends the keycode for the key `[` instead of keycode 229 (which indicates the character still need to be processed by the systems input method) im pretty sure it will be reflected as an error, and lower the accuracy.

I will look into the accuracy issue, so far it seems inconsistent.

**Comment by Miodec** [comment] 2020-05-20 15:42
Okay, i found and fixed the accuracy issue 274202119060e83e9541f74ea30a8da9894f74bb

**Comment by Miodec** [comment] 2020-05-20 15:50
What the fuck Firefox? When i press the `[` key three times in a row it sends 3 of the accent characters. The first two have the keycode 219 and the last one has the correct, 229 keycode.

??????????

**Comment by dcasado** [comment] 2020-05-21 09:08
I'm not sure how is the app implemented but could be that [keyCode](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) is deprecated? Maybe because it's deprecated it's doing strange things? Like I said I don't know, I'm just throwing ideas.

By the way thanks for all the effort looking into this.

**Comment by Miodec** [comment] 2020-05-21 13:23
Keycode was deprecated for exactly the same reason its beneficial to me - it was showing the same keycode for multiple characters (and in my opinion it was deprecated because mozilla didnt want to give a single keycode, `229`, for multiple characters).

I don't know. I need to detect when a character is still being processed by the input method (the underline, meaning it will be replaced on the next character), because if i dont the accuracy calculation will be all over the place, and also the character will be highlighted as an incorrect one, even though it still might change.

**Comment by Miodec** [comment] 2020-05-21 13:27
I could of course just say `if character typed == ´` then ignore it in the calculation, which would work for spanish. But the problem is other languages - because there you might have another key that works that way, or two, or in the case of korean - the whole goddamn keyboard. They have so many characters that each alpha key can be changed by the next one. 

I need a solution that works for every language, and so far, keycode 229 seems to be the only option that is also for some reason not supported by firefox.

**Comment by dcasado** [comment] 2020-05-24 09:45
I've been trying other web pages like yours and all of them seem to have problems with accents in some degree.
I hope they fix that bug.

**Comment by Miodec** [comment] 2020-10-29 01:00
Alright, little update - or could be a big one. I may have gotten accented characters working. Can you try now?

**Comment by dcasado** [comment] 2020-10-29 08:21
It works!! First I had the option layout override as "qwerty" (not sure why) and it didn't work but changing it to "default" worked like a charm. I only tried in Mac OS with Firefox and Chrome so not sure with other OS and browser combinations.

Thanks for this!

**Comment by jolefevre** [comment] 2020-10-29 09:02
Great news! It now works with most accents. 👌 

Still not working for circumflex accents (like `ê`, `ô`, `î`, `û`, etc.) though:  
![2020_10_29-09 59 09-screenshot](https://user-images.githubusercontent.com/7468027/97547162-c17b3780-19cd-11eb-9df1-d4609bb52876.gif)

**Comment by thiagomeireless** [comment] 2020-10-29 13:06
For me, the https://monkey-type-dev-67af4.web.app/ version is working perfectly for Portuguese language. Every accented character (circumflex included) worked: ```á à ã â ä ç```

**Comment by Miodec** [comment] 2020-10-29 13:59
@thiagomeireless what about on live? make sure you clear cache to get latest code.

@jolefevre maybe its the layout override, try disabling

**Comment by thiagomeireless** [comment] 2020-10-29 14:14
@Miodec on live it works for me on Firefox (Incognito window, no cache) but doesn't work on Chrome (Incognito window, no cache), while the link above works fine on both.

**Comment by Miodec** [comment] 2020-10-29 14:36
@thiagomeireless so, which characters are not working in chrome?

@jolefevre i tested the circumflex on the french keyboard layout and can confirm its working - its probably mt layout override messing it up

**Comment by thiagomeireless** [comment] 2020-10-29 17:02
@Miodec I'll try to record a video later, but no accented character works for me on chrome (again, Portuguese language). Examples: ã â á à

**Comment by jolefevre** [comment] 2020-10-29 17:30
I just removed the layout override (`azerty` to `default`) and it works. Thanks!

**Comment by Miodec** [comment] 2020-10-29 18:03
![image](https://user-images.githubusercontent.com/13181393/97613835-13917c80-1a11-11eb-989e-de8b06998271.png)

@thiagomeireless just tested it - works for me

**Comment by RafaelHerzog** [comment] 2020-10-29 21:39
Mine isn't working with accents in Portuguese as well, the dev version @thiagomeireless linked worked for me too. My layout is the default one and even testing with the default options it doesn't work.

I use chrome btw.

**Comment by thiagomeireless** [comment] 2020-10-30 13:07
@Miodec here's a video showing it works on Firefox but not on Chrome, while the other link you shared works fine: 

https://www.dropbox.com/s/3wcxjqkyenila8j/monkeytype-2020-10-30_10.00.39.mkv?dl=0

**Comment by AntoNoll** [comment] 2020-11-05 18:11
Hi all, 

I cannot type circumflex letters (i.e. â, ê etc.) with my keyboard. Basically, when I type "^" then the letter, only the letter without the accent appears. I am on Ubuntu 20.04, which may have an impact in the way dead keys are taken into account.

**Comment by jcastillopro** [comment] 2020-11-12 00:26
I also have problems with accented characters when trying in chrome from Ubuntu 20.04.1 LTS. doesn't seem to work.

**Comment by LidaAmengual** [comment] 2020-12-07 18:12
I have the same problem as all of you. I am IT teacher and I'd like to use it with my students. Everything works in my ubuntu and windows devices, the problem is that all my students use chromebooks and with chromebooks it looks like accents in spanish doesn't work. Any suggestion to solve it?

**Comment by Miodec** [comment] 2020-12-08 00:48
Its really hard to debug whats wrong on chromebooks without actually having access to one. Its weird that it works on chrome though. I think the only way this could be completely fixed is rewriting the input method completely, which could take time.

**Comment by f10kk** [comment] 2020-12-09 10:43
I had this accent problem for a while now (tested with french and german). It was happening on Chrome, Chromium and Edge. However, when I do not log in, using the defaults provided, just changing the language, it works. 
Changing the option **layout override** from **qwerty** to **default** was the issue (I use a custom keyboard layout under Win10, based on qwerty, adding accents through right alt key).

**Comment by AntoNoll** [comment] 2020-12-09 13:20
My issue is happening on Ubuntu, not on a chromebook. I think it is probably related to the way "^" inputs are managed in the OS. Could be interesting to see if it happens also in other Linux distributions, or other graphical environement. I use Gnome for information.

**Comment by Miodec** [comment] 2020-12-09 19:20
Yeah @f10kk , layout override is very basic and doesn't support dead keys and accents - that's why I always say the first thing to try is to set layout override to default - are you sure @LidaAmengual, @jcastillopro  you tried that? However as @AntoNoll said, could be a fundamental difference between different systems in how input is handled.

**Comment by thiagomeireless** [comment] 2020-12-09 19:54
Some extra feedback: I'm on Linux - Manjaro and been using `Portuguese (Brasil) - Default` for a long time.

Typing on Firefox is perfectly fine, all accents works (ex.: há, só, são)
Typing on Chrome/Chromium, accents doesn't work

Tried changing from `Default` keyboard to all other options, still no luck.

![image](https://user-images.githubusercontent.com/6698296/101680111-fce23a80-3a3e-11eb-9af2-232bedc549db.png)

Is there any other thing I could test to try fixing it on Chrome(ium)?

**Comment by SeerLite** [comment] 2020-12-23 22:26
@Miodec
> I think the only way this could be completely fixed is rewriting the input method completely, which could take time.

Something like reading input events from `#wordsInput` instead of individual keypresses, right? That's something I've been playing around with in #753, and I think I could make it work. Currently I just don't wanna change too much because I'm not sure how the keypresses all get used in the final calculation for WPM. For example, I see that the code stores the amount of time held down for each individual keypress (am I wrong?), and if we were to use input events, there might be some problems with that as it's not as precise as keydown (AFAIK).

Also, I wonder if you could set up a test server (I'm not sure how firebase works) with the last changes to #753? It's to let people in this thread check it out without having to set monkeytype up locally. Specifically I think it could work for those whose Desktop Environment take over all accents and stuff (GTK/Gnome/Ubuntu/IBus/etc). Maybe I'm wrong tho. Still I'd be really grateful if you could set it up!

**Comment by Miodec** [comment] 2020-12-24 00:07
@SeerLite Check out `contributing.md` for a guide on how to set up a local server.

Keypress down duration is not used for wpm calculation but is used to verify if the test duration lines up with the sum of all the key data.

Actual wpm is just calculated by the characters typed / 5. Key spacing and key duration is used for verification and anti cheat.

**Comment by SeerLite** [comment] 2020-12-24 01:42
I figured it out! https://monkeytype-e5da5.web.app/
@AntoNoll @jcastillopro @LidaAmengual Please check it out and tell me if it works. Make sure to do it on Firefox, since that's currently the only browser this works.

> Key spacing and key duration is used for verification and anti cheat.

Welp, then would be affected. I can't see a good solution to this problem.

**Comment by AntoNoll** [comment] 2021-01-07 18:16
I tried on Firefox and Ubuntu 20.04LTS and it did work! Well done.

**Comment by danielepusceddu** [comment] 2021-01-09 00:19
> I figured it out! https://monkeytype-e5da5.web.app/
> @AntoNoll @jcastillopro @LidaAmengual Please check it out and tell me if it works. Make sure to do it on Firefox, since that's currently the only browser this works.
I tested it and it does solve the problem. I am Italian and I can't use monkeytype to practice typing my language because of this issue. It would be great if it were fixed.

**Comment by SeerLite** [comment] 2021-01-09 03:29
Nice to hear it's working for some people! I'm still trying to figure out how to do it on Chromium though since it sends different key codes.

Also, @Miodec what do you think about the implementation? I haven't looked at how the key duration and/or anti cheat works, but from what I can gather this is gonna break it.

**Comment by vitorstaycharlie** [comment] 2021-03-26 23:49
Accented characters and "ç" aren't working on Firefox and Google Chrome for me. I'm using Ubuntu 18.04.5 LTS

**Comment by vitoryugulis** [comment] 2021-03-26 23:51
Accented characters and "ç" aren't working on Firefox and Google Chrome for me. I'm using Ubuntu 18.04.5 LTS

**Comment by thiagomeireless** [comment] 2021-03-27 00:10
Same here. In my previous comment a few months ago, it was working fine in Firefox, now it doesn't work anymore.

**Comment by Miodec** [comment] 2021-04-30 20:05
Could anyone that is having dead key issues take a look at #1325? There is a link at the top to test the change.

**Comment by thiagomeireless** [comment] 2021-05-01 02:14
Hey @Miodec, the accented/dead key issues were resolved in that version, but there's a new bug in my case where the first letter is always wrong. If I backspace and type again, it works fine.


https://user-images.githubusercontent.com/6698296/116767956-b602da80-aa09-11eb-9888-48a473c151d0.mp4

**Comment by poochie2** [comment] 2021-07-05 21:35
My 2c: seems to work fine in FF, not in Chrome. Using Colemak layout for Italian accendet letters (https://colemak.com/Multilingual).

**Comment by Miodec** [comment] 2021-09-29 14:44
The inupt rewrite is live now on the main site. Give it a quick test and let me know.

**Comment by victante** [comment] 2021-09-29 15:32
Can confirm that accented characters are working great for me on the main site. Thanks!

**Closed** 2021-09-29 23:22 UTC
Labels: stuck
